#pragma once
#include <SFML/Graphics.hpp>

namespace Game{
    /*
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING I HATE SFML I HATE TEMPLATING 
    */

    enum class EventType : int {
        Closed = 0,
        KeyPressed,
        KeyReleased,
        MouseButtonPressed,
        MouseButtonReleased,
        MouseMoved,
        MouseWheelScrolled,
        Resized,
        TextEntered,
        Count
    };
    
    inline EventType getEventType(const sf::Event& event) {
        if (event.is<sf::Event::Closed>()) return EventType::Closed;
        if (event.is<sf::Event::KeyPressed>()) return EventType::KeyPressed;
        if (event.is<sf::Event::KeyReleased>()) return EventType::KeyReleased;
        if (event.is<sf::Event::MouseButtonPressed>()) return EventType::MouseButtonPressed;
        if (event.is<sf::Event::MouseButtonReleased>()) return EventType::MouseButtonReleased;
        if (event.is<sf::Event::MouseMoved>()) return EventType::MouseMoved;
        if (event.is<sf::Event::MouseWheelScrolled>()) return EventType::MouseWheelScrolled;
        if (event.is<sf::Event::Resized>()) return EventType::Resized;
        if (event.is<sf::Event::TextEntered>()) return EventType::TextEntered;
        return EventType::Closed; 
    }


}